- id: '1546210609741'
  alias: Morning Automation
  trigger:
  - at: '8:45'
    platform: time
  condition: []
  action:
  - data: {}
    service: script.white
  - data: {}
    entity_id: input_boolean.awake
    service: input_boolean.turn_on
  initial_state: false
  mode: single
- id: 43a25b65afed4a4680f5ec81172f11e8
  alias: Set iOS Theme At Startup
  trigger:
  - event: start
    platform: homeassistant
  action:
  - data:
      name: ios-dark-mode
    service: frontend.set_theme
  initial_state: true
- id: '1617634628204'
  alias: Automating
  description: Reset automating bool used for light switch
  trigger:
  - platform: state
    entity_id: input_boolean.automating
    to: 'on'
  condition: []
  action:
  - wait_template: ''
    timeout: '1.8'
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.automating
  mode: single
- id: '1620642299524'
  alias: Motion Bypass
  description: Turn lights on if bed motion sensing bypass is enabled
  trigger:
  - platform: state
    entity_id: input_boolean.bedmotion
    to: 'on'
  condition:
  - condition: state
    entity_id: light.fan_lights
    state: 'off'
  action:
  - service: script.white
  mode: single
- id: '1620642346363'
  alias: Ensure Stuff Off
  description: Turn off room at 7 AM
  trigger:
  - platform: time
    at: '7:00'
  condition: []
  action:
  - service: script.stuff_off
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.awake
  mode: single
- id: '1620642580296'
  alias: Bed Motion
  description: If motion detected in bed under certain circumstances, turn off overhead
    lights.
  trigger:
  - platform: state
    entity_id: binary_sensor.wyzemotion
    to: 'on'
  condition:
  - condition: state
    entity_id: light.fan_lights
    state: 'on'
  - condition: state
    entity_id: binary_sensor.bedroom_door
    state: 'off'
  - condition: state
    entity_id: input_boolean.bedmotion
    state: 'off'
  action:
  - service: script.fan_off
  mode: single
- id: '1620643134568'
  alias: Wyze Power
  description: Control power to Bedroom Wyze camera based on home presence
  trigger:
  - platform: time_pattern
    minutes: /1
  - platform: zone
    entity_id: person.anthony
    zone: zone.home
    event: enter
  - platform: zone
    entity_id: person.anthony
    zone: zone.home
    event: leave
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: person.anthony
        state: home
      sequence:
      - condition: state
        entity_id: switch.power_strip_outlet_2
        state: 'on'
      - service: switch.turn_off
        target:
          entity_id: switch.power_strip_outlet_2
    default:
    - condition: state
      entity_id: switch.power_strip_outlet_2
      state: 'off'
    - service: switch.turn_on
      target:
        entity_id: switch.power_strip_outlet_2
  mode: single
- id: '1620710706685'
  alias: Color Loop
  description: Adjust color loop state
  trigger:
  - platform: time_pattern
    seconds: /3
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_number.colorloopstate
        state: '4.0'
      sequence:
      - service: input_number.set_value
        target:
          entity_id: input_number.colorloopstate
        data:
          value: 0
    default:
    - service: input_number.increment
      target:
        entity_id: input_number.colorloopstate
  mode: single
- id: '1620906849721'
  alias: Motion Alert
  description: ''
  use_blueprint:
    path: vorion/send-camera-snapshot-notification-on-motion.yaml
    input:
      notification_message: Movement was detected in bedroom
      motion_sensor: group.bedroom_motion
      camera: camera.bedroom
      notify_device: 0429e9d5aa6e19cfa793f8db0a8586a6
      is_ios: true
      notification_title: Motion detected in bedroom.
      delay: 1
- id: '1621577255605'
  alias: Keep Off
  description: Keeps stuff off if not home
  trigger:
  - platform: state
    entity_id: light.desk_lights
    from: 'off'
    to: 'on'
    for: 00:05:00
  - platform: state
    entity_id: light.fan_lights
    from: 'off'
    to: 'on'
    for: 00:05:00
  - platform: state
    entity_id: switch.windows
    for: 00:01:00
    from: 'off'
    to: 'on'
  - platform: zone
    entity_id: person.anthony
    zone: zone.home
    event: leave
  condition:
  - condition: template
    value_template: '{{states(''person.anthony'') != ''home''}}'
  action:
  - service: script.stuff_off
  - service: cover.close_cover
    target:
      entity_id: cover.bedroom_blinds
  mode: single
- id: '1621816232606'
  alias: Taylor Wyze Power
  description: Control power to Apartment Wyze cameras based on home presence
  trigger:
  - platform: time_pattern
    minutes: /1
  - platform: zone
    entity_id: person.taylor
    zone: zone.taylor_s_home
    event: enter
  - platform: zone
    entity_id: person.taylor
    zone: zone.taylor_s_home
    event: leave
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: person.taylor
        state: Taylor's Home
      sequence:
      - condition: state
        entity_id: group.apartment
        state: 'on'
      - service: homeassistant.turn_off
        target:
          entity_id: group.apartment
    default:
    - condition: state
      entity_id: group.apartment
      state: 'off'
    - service: homeassistant.turn_on
      target:
        entity_id: group.apartment
  mode: single
- id: '1627401846713'
  alias: Arrived home in bedroom
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.bedroom_door
    to: 'on'
    from: 'off'
  condition:
  - condition: state
    entity_id: input_select.anthony
    state: Just Arrived
  action:
  - service: script.stuff_on
  - condition: sun
    after: sunset
  - service: cover.open_cover
    target:
      entity_id: cover.bedroom_blinds
  mode: single
- id: '1627443167507'
  alias: Window Alert
  description: Alert if Window Opened while Away
  trigger:
  - platform: state
    entity_id: binary_sensor.window
    from: closed
    to: open
  condition:
  - condition: template
    value_template: '{{states(''person.anthony'') != ''home''}}'
  action:
  - service: notify.mobile_app_iphone
    data:
      message: Bedroom Window has been opened
      title: Window Opened
  mode: single
- id: '1627443803522'
  alias: AC Auto Off When Leaving
  description: ''
  trigger:
  - platform: zone
    entity_id: person.anthony
    zone: zone.home
    event: leave
  condition:
  - condition: state
    entity_id: switch.ac
    state: 'on'
  action:
  - service: script.1620182520614
  mode: single
- id: '1627447111302'
  alias: Set Correct Location on Startup
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition:
  - condition: zone
    entity_id: person.anthony
    zone: zone.home
  action:
  - service: input_select.select_option
    target:
      entity_id: input_select.anthony
    data:
      option: Home
  mode: single
- id: '1627448446635'
  alias: Update Fyrtur State
  description: ''
  trigger:
  - platform: time_pattern
    seconds: /8
  condition: []
  action:
  - service: homeassistant.update_entity
    target:
      entity_id: cover.bedroom_blinds
  mode: single
- id: '1627534142796'
  alias: Auto Open Blinds Past Sunset if Home
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition:
  - condition: zone
    entity_id: person.anthony
    zone: zone.home
  action:
  - service: cover.open_cover
    target:
      entity_id: cover.bedroom_blinds
  mode: single
- id: '1627702427940'
  alias: Dlink Error Count
  description: ''
  trigger:
  - platform: event
    event_type: system_log_event
    event_data:
      name: custom_components.dlink_hnap.binary_sensor
  - platform: event
    event_type: system_log_event
    event_data:
      name: custom_components.dlink_hnap.dlink
  condition: []
  action:
  - service: input_number.increment
    target:
      entity_id: input_number.d_link_errors
  mode: parallel
  max: 10
- id: '1627702938295'
  alias: Dlink Reset
  description: ''
  trigger:
  - platform: state
    entity_id: automation.dlink_error_count
    to: '40'
  condition: []
  action:
  - service: switch.turn_off
    target:
      entity_id:
      - switch.d_link_plug
      - switch.power_strip_outlet_4
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - service: switch.turn_on
    target:
      entity_id:
      - switch.d_link_plug
      - switch.power_strip_outlet_4
  - delay:
      hours: 0
      minutes: 0
      seconds: 38
      milliseconds: 0
  - service: input_number.set_value
    target:
      entity_id: input_number.d_link_errors
    data:
      value: 0
  mode: single
