- id: '1546210609741'
  alias: Morning Automation
  trigger:
  - at: '8:45'
    platform: time
  condition: []
  action:
  - data: {}
    service: script.white
  - data: {}
    entity_id: input_boolean.awake
    service: input_boolean.turn_on
  initial_state: false
  mode: single
- id: 43a25b65afed4a4680f5ec81172f11e8
  alias: Startup Actions
  description: Set Theme, Ensure Location Input Select is Updated
  trigger:
  - event: start
    platform: homeassistant
  action:
  - data:
      name: ios-dark-mode
    service: frontend.set_theme
  - condition: zone
    entity_id: person.anthony
    zone: zone.home
  - service: input_select.select_option
    target:
      entity_id: input_select.anthony
    data:
      option: Home
  initial_state: true
  mode: single
- id: '1617634628204'
  alias: Automating
  description: Reset automating bool used for light switch
  trigger:
  - platform: state
    entity_id: input_boolean.automating
    to: 'on'
  condition: []
  action:
  - wait_template: ''
    timeout: '1.8'
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.automating
  mode: single
- id: '1620642299524'
  alias: Motion Bypass
  description: Turn lights on if bed motion sensing bypass is enabled
  trigger:
  - platform: state
    entity_id: input_boolean.bedmotion
    to: 'on'
  condition:
  - condition: state
    entity_id: light.fan_lights
    state: 'off'
  action:
  - service: script.white
  mode: single
- id: '1620642346363'
  alias: Ensure Stuff Off
  description: Turn off room at 7 AM
  trigger:
  - platform: time
    at: '7:00'
  condition: []
  action:
  - service: script.stuff_off
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.awake
  mode: single
- id: '1620642580296'
  alias: Bed Motion
  description: If motion detected in bed under certain circumstances, turn off overhead
    lights.
  trigger:
  - platform: state
    entity_id: binary_sensor.wyzemotion
    to: 'on'
  condition:
  - condition: state
    entity_id: light.fan_lights
    state: 'on'
  - condition: state
    entity_id: binary_sensor.bedroom_door
    state: 'off'
  - condition: state
    entity_id: input_boolean.bedmotion
    state: 'off'
  action:
  - service: script.fan_off
  mode: single
- id: '1620643134568'
  alias: Wyze Power
  description: Control power to Bedroom Wyze camera based on home presence
  trigger:
  - platform: time_pattern
    minutes: /1
  - platform: zone
    entity_id: person.anthony
    zone: zone.home
    event: enter
  - platform: zone
    entity_id: person.anthony
    zone: zone.home
    event: leave
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: person.anthony
        state: home
      sequence:
      - condition: state
        entity_id: switch.power_strip_outlet_2
        state: 'on'
      - service: switch.turn_off
        target:
          entity_id: switch.power_strip_outlet_2
    default:
    - condition: state
      entity_id: switch.power_strip_outlet_2
      state: 'off'
    - service: switch.turn_on
      target:
        entity_id: switch.power_strip_outlet_2
  mode: single
- id: '1620710706685'
  alias: Color Loop
  description: Adjust color loop state
  trigger:
  - platform: time_pattern
    seconds: /3
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: input_number.colorloopstate
        state: '4.0'
      sequence:
      - service: input_number.set_value
        target:
          entity_id: input_number.colorloopstate
        data:
          value: 0
    default:
    - service: input_number.increment
      target:
        entity_id: input_number.colorloopstate
  mode: single
- id: '1620906849721'
  alias: Motion Alert
  description: ''
  use_blueprint:
    path: vorion/send-camera-snapshot-notification-on-motion.yaml
    input:
      notification_message: Movement was detected in bedroom
      motion_sensor: group.bedroom_motion
      camera: camera.bedroom
      notify_device: 0429e9d5aa6e19cfa793f8db0a8586a6
      is_ios: true
      notification_title: Motion detected in bedroom.
      delay: 1
- id: '1621577255605'
  alias: Left Home
  description: Turns bedroom off when leaving home, and ensures bedroom stays off
  trigger:
  - platform: state
    entity_id: light.desk_lights
    from: 'off'
    to: 'on'
    for: 00:05:00
  - platform: state
    entity_id: light.fan_lights
    from: 'off'
    to: 'on'
    for: 00:05:00
  - platform: state
    entity_id: switch.windows
    for: 00:01:00
    from: 'off'
    to: 'on'
  - platform: zone
    entity_id: person.anthony
    zone: zone.home
    event: leave
  condition:
  - condition: template
    value_template: '{{states(''person.anthony'') != ''home''}}'
  action:
  - service: script.stuff_off
  - service: cover.close_cover
    target:
      entity_id: cover.bedroom_blinds
  - condition: state
    entity_id: switch.ac
    state: 'on'
  - service: script.1620182520614
  mode: single
- id: '1621816232606'
  alias: Taylor Wyze Power
  description: Control power to Apartment Wyze cameras based on home presence
  trigger:
  - platform: time_pattern
    minutes: /1
  - platform: zone
    entity_id: person.taylor
    zone: zone.taylor_s_home
    event: enter
  - platform: zone
    entity_id: person.taylor
    zone: zone.taylor_s_home
    event: leave
  condition: []
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: person.taylor
        state: Taylor's Home
      sequence:
      - condition: state
        entity_id: group.apartment
        state: 'on'
      - service: homeassistant.turn_off
        target:
          entity_id: group.apartment
    default:
    - condition: state
      entity_id: group.apartment
      state: 'off'
    - service: homeassistant.turn_on
      target:
        entity_id: group.apartment
  mode: single
- id: '1627401846713'
  alias: Arrived Home
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.bedroom_door
    to: 'on'
    from: 'off'
  condition:
  - condition: state
    entity_id: input_select.anthony
    state: Just Arrived
  action:
  - choose:
    - conditions:
      - condition: sun
        after: sunset
        after_offset: -01:00:00
      sequence:
      - service: cover.open_cover
        target:
          entity_id: cover.bedroom_blinds
      - service: script.stuff_on
      - service: input_select.select_option
        target:
          entity_id: input_select.anthony
        data:
          option: Home
    default:
    - service: script.stuff_on
    - service: input_select.select_option
      target:
        entity_id: input_select.anthony
      data:
        option: Home
  mode: single
- id: '1627443167507'
  alias: Window Alert
  description: Alert if Window Opened while Away
  trigger:
  - platform: state
    entity_id: binary_sensor.window
    from: closed
    to: open
  condition:
  - condition: template
    value_template: '{{states(''person.anthony'') != ''home''}}'
  action:
  - service: notify.mobile_app_iphone
    data:
      message: Bedroom Window has been opened
      title: Window Opened
  mode: single
- id: '1627448446635'
  alias: Update Fyrtur State
  description: ''
  trigger:
  - platform: time_pattern
    seconds: /8
  condition: []
  action:
  - service: homeassistant.update_entity
    target:
      entity_id: cover.bedroom_blinds
  mode: single
- id: '1627534142796'
  alias: Auto Open Blinds Past Sunset if Home
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: -01:00:00
  condition:
  - condition: zone
    entity_id: person.anthony
    zone: zone.home
  - condition: not
    conditions:
    - condition: state
      entity_id: input_select.anthony
      state: Just Arrived
  action:
  - service: cover.open_cover
    target:
      entity_id: cover.bedroom_blinds
  mode: single
- id: '1627702427940'
  alias: D-Link Motion Sensor Reset
  description: Resets D-Link motion sensors when connection is lost
  trigger:
  - platform: event
    event_type: system_log_event
    event_data:
      name: custom_components.dlink_hnap.binary_sensor
  - platform: event
    event_type: system_log_event
    event_data:
      name: custom_components.dlink_hnap.dlink
  - platform: numeric_state
    entity_id: input_number.d_link_errors
    above: '20'
  condition: []
  action:
  - service: input_number.increment
    target:
      entity_id: input_number.d_link_errors
  - condition: numeric_state
    entity_id: input_number.d_link_errors
    above: '20'
  - service: switch.turn_off
    target:
      entity_id:
      - switch.d_link_plug
      - switch.power_strip_outlet_4
  - delay:
      hours: 0
      minutes: 0
      seconds: 0
      milliseconds: 500
  - service: switch.turn_on
    target:
      entity_id:
      - switch.d_link_plug
      - switch.power_strip_outlet_4
  - delay:
      hours: 0
      minutes: 0
      seconds: 38
      milliseconds: 0
  - service: input_number.set_value
    target:
      entity_id: input_number.d_link_errors
    data:
      value: 0
  mode: single
  max: 10
- id: '1627726771287'
  alias: Mark Anthony as Just Arrived
  description: ''
  trigger:
  - platform: zone
    entity_id: person.anthony
    zone: zone.home
    event: enter
  condition: []
  action:
  - service: input_select.select_option
    target:
      entity_id: input_select.anthony
    data:
      option: Just Arrived
  mode: parallel
  max: 10
- id: '1627727014507'
  alias: Mark Anthony as Just Left
  description: ''
  trigger:
  - platform: zone
    entity_id: person.anthony
    zone: zone.home
    event: leave
  condition: []
  action:
  - service: input_select.select_option
    target:
      entity_id: input_select.anthony
    data:
      option: Just Left
  mode: parallel
  max: 10
- id: '1627778209718'
  alias: Mark Anthony as Home
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.anthony
    to: Just Arrived
    for: 00:10:00
  condition: []
  action:
  - service: input_select.select_option
    target:
      entity_id: input_select.anthony
    data:
      option: Home
  mode: single
- id: '1627778293785'
  alias: Mark Anthony as Away
  description: ''
  trigger:
  - platform: state
    entity_id: input_select.anthony
    to: Just Left
    for: 00:10:00
  condition: []
  action:
  - service: input_select.select_option
    target:
      entity_id: input_select.anthony
    data:
      option: Away
  mode: single
- id: '1627779396737'
  alias: Door Opened
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.bedroom_door
    to: 'on'
  condition:
  - condition: state
    entity_id: input_select.anthony
    state: Home
  - condition: state
    entity_id: light.fan_lights
    state: 'off'
  action:
  - choose:
    - conditions:
      - condition: state
        entity_id: light.desk_lights
        state: 'on'
      - condition: time
        after: 07:00:00
        before: 01:00:00
      sequence:
      - service: script.color_loop
    - conditions:
      - condition: state
        entity_id: light.desk_lights
        state: 'off'
      - condition: state
        entity_id: automation.morning_lights_on
        state: 'on'
      - condition: state
        entity_id: input_boolean.awake
        state: 'off'
      - condition: time
        after: 07:01
        before: '16:00'
      sequence:
      - service: homeassistant.turn_on
        target:
          entity_id:
          - script.stuff_on
          - input_boolean.awake
    default: []
  mode: single
- id: '1627779717449'
  alias: Night Light
  description: WIP
  trigger:
  - platform: state
    entity_id: group.bedroom_motion
    to: 'on'
  condition:
  - condition: zone
    entity_id: person.anthony
    zone: zone.home
  - condition: time
    after: '17:00:00'
    before: 09:00:00
  - condition: state
    entity_id: light.bed_lights
    state: 'off'
  action:
  - service: light.turn_on
    target:
      entity_id: light.bed_lights
    data:
      transition: 1
      rgb_color: 255,255,255
      brightness_pct: 45
  mode: single
- id: '1627790661607'
  alias: Low battery level detection & notification for all battery sensors
  description: ''
  use_blueprint:
    path: sbyx/low-battery-level-detection-notification-for-all-battery-sensors.yaml
    input:
      time: '17:00:00'
      exclude:
        entity_id:
        - sensor.iphone_battery_level
        - sensor.ipad_battery_level
      actions:
      - service: notify.mobile_app_iphone
        data:
          title: Sensor Battery Low
          message: '{{sensors}} is low. Replace soon.'
