- platform: ping
  host: !secret host
  name: Desktop Power
- platform: workday
  country: US
  days_offset: 1
- platform: generic_hygrostat
  name: Shower
  sensor: sensor.acurite_humidity
  delta_trigger: 4
  target_offset: 5
  min_on_time: 240
  max_on_time: 1800
  sample_interval: 5
#  min_humidity: 55
  unique_id: shower