- platform: mqtt
  name: "Front Porch Motion"
  state_topic: "FP"
  payload_on: "on"
  payload_off: "off"
  off_delay: 30
  device_class: motion
- platform: mqtt
  name: "Car Motion"
  state_topic: "car"
  payload_on: "on"
  payload_off: "off"
  off_delay: 30
  device_class: motion
- platform: ping
  name: "Master Bedroom G1100"
  host: 192.168.1.254
  scan_interval: 6