- platform: generic_hygrostat
  name: Shower
  sensor: sensor.acurite_bathroom_humidity
  delta_trigger: 4
  target_offset: 6
  min_on_time: 5
  max_on_time: 1200
  sample_interval: 3
#  min_humidity: 55
  unique_id: shower