- platform: mqtt
  name: "Front Porch Motion"
  state_topic: "FP"
  payload_on: "on"
  off_delay: 600000
  device_class: motion
- platform: mqtt
  name: "Backyard Motion"
  state_topic: "backyard"
  payload_on: "on"
  off_delay: 600000
  device_class: motion