- platform: mjpeg
  mjpeg_url: !secret living_room_camera
  name: Living Room
  still_image_url: !secret living_room_camera_image
- platform: mjpeg
  mjpeg_url: !secret front_porch_camera
  name: Front Porch
  still_image_url: !secret front_porch_camera_image
- platform: mjpeg
  mjpeg_url: !secret bedroom_camera
  name: Bedroom
  still_image_url: !secret bedroom_camera_image
- platform: mjpeg
  mjpeg_url: !secret garage_camera
  name: Garage 
  still_image_url: !secret garage_camera_image