- platform: mjpeg
  mjpeg_url: http://192.168.1.88:81/mjpg/LR/video.mjpg
  name: Living Room
- platform: mjpeg
  mjpeg_url: http://192.168.1.88:81/mjpg/FP/video.mjpg
  name: Front Porch
- platform: mjpeg
  mjpeg_url: http://192.168.1.88:81/mjpg/BR/video.mjpg
  name: Bedroom
- platform: mjpeg
  mjpeg_url: http://192.168.1.88:81/mjpg/garage/video.mjpg
  name: Garage