- platform: mjpeg
  mjpeg_url: http://maihome.duckdns.org:81/mjpg/LR
  name: Living Room
  still_image_url: http://maihome.duckdns.org:81/image/LR
- platform: mjpeg
  mjpeg_url: http://maihome.duckdns.org:81/mjpg/FP
  name: Front Porch
  still_image_url: http://maihome.duckdns.org:81/image/FP
- platform: mjpeg
  mjpeg_url: http://maihome.duckdns.org:81/mjpg/BR
  name: Bedroom
  still_image_url: http://maihome.duckdns.org:81/image/BR
- platform: mjpeg
  mjpeg_url: http://maihome.duckdns.org:81/mjpg/garage
  name: Garage 
  still_image_url: http://maihome.duckdns.org:81/image/garage