default_config:
logbook: !include logbook.yaml
automation: !include automations.yaml
history: !include history.yaml
frontend: !include themes.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
group: !include groups.yaml
alexa: !include alexa.yaml
switch: !include switch.yaml
light: !include light.yaml
sensor: !include sensor.yaml
wake_on_lan:

homeassistant:
  customize: !include customize.yaml

#reduce db size
recorder:
  purge_keep_days: 3

# reduce login failure messages
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 172.16.0.0/12
    - 192.168.1.0/24
    - ::1

weather:
  - platform: darksky
    api_key: !secret darksky

template:
  - binary_sensor:
      - name: "Discord Active"
        state: >
          {{ states('sensor.discord')|float(-1) > 0}}

life360: # location disabled
  members:
    exclude: Anthony Maiorani

mqtt:
  binary_sensor:
    - state_topic: "FP"
      name: "Front Porch Motion"
      payload_on: "on"
      off_delay: 600000
      device_class: motion
    - state_topic: "backyard"
      name: "Backyard Motion"
      payload_on: "on"
      off_delay: 600000
      device_class: motion