default_config:
logbook: !include logbook.yaml
automation: !include automations.yaml
history: !include history.yaml
frontend: !include themes.yaml
script: !include scripts.yaml
group: !include groups.yaml
alexa: !include alexa.yaml
switch: !include switch.yaml
light: !include light.yaml
sensor: !include sensor.yaml
binary_sensor: !include binary_sensor.yaml
wake_on_lan:

homeassistant:
  customize: !include customize.yaml

#reduce db size
recorder:
  purge_keep_days: 3

# reduce login failure messages
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - 172.16.0.0/12
    - 192.168.1.0/24
    - ::1

weather:
  - platform: darksky
    api_key: !secret darksky

template:
  - binary_sensor:
      - name: "Discord Active"
        state: >
          {{ states('sensor.discord')|float(-1) > 0}}
      - name: "Bedroom On"
        state: >
          {{ is_state('light.bedroom_lights', 'on') }}
  - sensor:
      - name: "AC Thermostat Temperature"
        state: >
          {% if is_state("input_boolean.ac_boost", "on") -%} 61 
          {% elif is_state("binary_sensor.bedroom_door", "on") -%} 76
          {% elif is_state("switch.desktop", "on") -%} 75
          {% elif is_state("light.fan_lights", "on") -%} 73 
          {%- else -%} 71
          {%- endif %}
  - sensor:
      - name: "Alarm Display"
        state: >
          {% if states.sensor.bedroom_dot_next_alarm.state == "unavailable" -%} 0
          {% elif as_datetime(states.sensor.bedroom_dot_next_alarm.state).day - now().day > 1 -%} 0
          {% elif as_datetime(states.sensor.bedroom_dot_next_alarm.state).day != now().day -%}
          {{ (as_datetime(states.sensor.bedroom_dot_next_alarm.state).strftime("%s") | int) | timestamp_custom("%A at %-I:%M %p", false) }}
          {%- else -%} 
          {{ (as_datetime(states.sensor.bedroom_dot_next_alarm.state).strftime("%s") | int) | timestamp_custom("%-I:%M %p", false) }}
          {%- endif %}

mqtt:
  binary_sensor:
    - state_topic: "FP"
      name: "Front Porch Motion"
      payload_on: "on"
      off_delay: 600000
      device_class: motion
    - state_topic: "backyard"
      name: "Backyard Motion"
      payload_on: "on"
      off_delay: 600000
      device_class: motion