- platform: group
  name: Bedroom Lights
  entities:
    - light.bed_lights
    - light.smart_bulb_1
    - light.smart_bulb_2
    - light.smart_bulb_3
    - light.desk_lights
    - light.rgb_light_switch
    - light.rgb_light_switch_corner
- platform: group
  name: LED Strips
  entities:
    - light.bed_lights
    - light.desk_lights
    - light.closet_lights
- platform: group
  name: Fan Lights
  entities:
    - light.smart_bulb_1
    - light.smart_bulb_2
    - light.smart_bulb_3