- platform: group
  name: Bedroom Lights
  unique_id: bedroom_lights
  entities:
    - light.wyze_bulb_1
    - light.wyze_bulb_2
    - light.wyze_bulb_3
    - light.light_switch
    - light.light_switch_corner
- platform: group
  unique_id: fan_lights
  name: Fan Lights
  entities:
    - light.wyze_bulb_1
    - light.wyze_bulb_2
    - light.wyze_bulb_3
- platform: template
  lights:
    wled:
      unique_id: wled
      friendly_name: WLED
      level_template: "{{ states('input_number.wled_brightness') }}"
      value_template: "{{ is_state('switch.wled', 'on') }}"
      effect_list_template: "{{ state_attr('input_select.wled_preset', 'options') }}"
      effect_template: "{{ states('input_select.wled_preset') }}"
      turn_on:
        service: switch.turn_on
        data:
            entity_id: switch.wled
      turn_off:
        service: switch.turn_off
        data:
            entity_id: switch.wled
      set_level:
        - service: input_number.set_value
          data:
            value: "{{ brightness }}"
            entity_id: input_number.wled_brightness
        - service: rest_command.set_wled_brightness
      set_effect:
        - service: input_select.select_option
          data:
            option: "{{ effect }}"
          target:
            entity_id: input_select.wled_preset
        - service: rest_command.set_wled_preset
    bed:
      unique_id: bed
      friendly_name: bed
      level_template: "{{ states('input_number.bed_brightness') }}"
      value_template: "{{ is_state('switch.bed', 'on') }}"
      turn_on:
        service: switch.turn_on
        data:
            entity_id: switch.bed
      turn_off:
        service: switch.turn_off
        data:
            entity_id: switch.bed
      set_level:
        - service: input_number.set_value
          data:
            value: "{{ brightness }}"
            entity_id: input_number.bed_brightness
        - service: rest_command.set_bed_brightness
    rope:
      unique_id: rope
      friendly_name: Rope
      level_template: "{{ states('input_number.rope_brightness') }}"
      value_template: "{{ is_state('switch.rope', 'on') }}"
      turn_on:
        service: switch.turn_on
        data:
            entity_id: switch.rope
      turn_off:
        service: switch.turn_off
        data:
            entity_id: switch.rope
      set_level:
        - service: input_number.set_value
          data:
            value: "{{ brightness }}"
            entity_id: input_number.rope_brightness
        - service: rest_command.set_rope_brightness
    lamp1:
      unique_id: lamp1
      friendly_name: Lamp 1
      level_template: "{{ states('input_number.lamp_1_brightness') }}"
      value_template: "{{ is_state('switch.lamp_1', 'on') }}"
      turn_on:
        service: switch.turn_on
        data:
            entity_id: switch.lamp_1
      turn_off:
        service: switch.turn_off
        data:
            entity_id: switch.lamp_1
      set_level:
        - service: input_number.set_value
          data:
            value: "{{ brightness }}"
            entity_id: input_number.lamp_1_brightness
        - service: rest_command.set_lamp_1_brightness
    lamp2:
      unique_id: lamp2
      friendly_name: Lamp 2
      level_template: "{{ states('input_number.lamp_2_brightness') }}"
      value_template: "{{ is_state('switch.lamp_2', 'on') }}"
      turn_on:
        service: switch.turn_on
        data:
            entity_id: switch.lamp_2
      turn_off:
        service: switch.turn_off
        data:
            entity_id: switch.lamp_2
      set_level:
        - service: input_number.set_value
          data:
            value: "{{ brightness }}"
            entity_id: input_number.lamp_2_brightness
        - service: rest_command.set_lamp_2_brightness
    govee:
      unique_id: govee
      friendly_name: Govee
      level_template: "{{ states('input_number.govee_brightness') }}"
      value_template: "{{ is_state('switch.govee', 'on') }}"
      effect_list_template: "{{ state_attr('input_select.govee_preset', 'options') }}"
      effect_template: "{{ states('input_select.govee_preset') }}"
      turn_on:
        service: switch.turn_on
        data:
            entity_id: switch.govee
      turn_off:
        service: switch.turn_off
        data:
            entity_id: switch.govee
      set_level:
        - service: input_number.set_value
          data:
            value: "{{ brightness }}"
          target:
            entity_id: input_number.govee_brightness
        - service: rest_command.set_govee_brightness
      set_effect:
        - service: input_select.select_option
          data:
            option: "{{ effect }}"
          target:
            entity_id: input_select.govee_preset
        - service: rest_command.set_govee_preset