- platform: group
  name: Bedroom Lights
  unique_id: bedroom_lights
  entities:
    - light.bed_lights
    - light.wyze_bulb_1
    - light.wyze_bulb_2
    - light.wyze_bulb_3
    - light.desk_lights
    - light.light_switch
    - light.light_switch_corner
- platform: group
  unique_id: led_strips
  name: LED Strips
  entities:
    - light.bed_lights
    - light.desk_lights
    - light.closet_lights
- platform: group
  unique_id: fan_lights
  name: Fan Lights
  entities:
    - light.wyze_bulb_1
    - light.wyze_bulb_2
    - light.wyze_bulb_3
- platform: group
  unique_id: evan_fan
  name: Evan Fan
  entities:
    - light.hue_color_lamp_1
    - light.hue_color_lamp_2
    - light.smart_bulb_1
    - light.smart_bulb_2
    - light.smart_bulb_3
    - light.wyze_bulb_5
    - light.wyze_bulb_4