- platform: universal
  name: Kitchen Speakers
  children:
    - media_player.owntone_output_kitchen_left
    - media_player.owntone_output_kitchen_right
  attributes:
    state: media_player.owntone_output_kitchen_left
    volume_level: media_player.owntone_output_kitchen_left|volume_level
  commands:
    turn_on:
      service: media_player.turn_on
      target:
        entity_id: 
          - media_player.owntone_output_kitchen_left
          - media_player.owntone_output_kitchen_right
    turn_off:
      service: media_player.turn_off
      target:
        entity_id: 
          - media_player.owntone_output_kitchen_left
          - media_player.owntone_output_kitchen_right
    set_volume:
      service: media_player.volume_set
      data:
        volume_level: "{{ volume_level }}"
      target:
        entity_id:
          - media_player.owntone_output_kitchen_left
          - media_player.owntone_output_kitchen_right
  device_class: speaker
  unique_id: kitchen_speakers
- platform: universal
  name: Guest Speakers
  children:
    - media_player.owntone_output_guest_left
    - media_player.owntone_output_guest_right
  attributes:
    state: media_player.owntone_output_guest_left
    volume_level: media_player.owntone_output_guest_left|volume_level
  commands:
    turn_on:
      service: media_player.turn_on
      target:
        entity_id: 
          - media_player.owntone_output_guest_left
          - media_player.owntone_output_guest_right
    turn_off:
      service: media_player.turn_off
      target:
        entity_id: 
          - media_player.owntone_output_guest_left
          - media_player.owntone_output_guest_right
    set_volume:
      service: media_player.volume_set
      data:
        volume_level: "{{ volume_level }}"
      target:
        entity_id:
          - media_player.owntone_output_guest_left
          - media_player.owntone_output_guest_right
  device_class: speaker
  unique_id: guest_speakers