- platform: universal
  name: Kitchen Speakers
  children:
    - media_player.owntone_output_kitchen_homepod
    - media_player.owntone_output_kitchen_right
  commands:
    turn_on:
      service: media_player.turn_on
      target:
        entity_id: 
          - media_player.owntone_output_kitchen_homepod
          - media_player.owntone_output_kitchen_right
    turn_off:
      service: media_player.turn_off
      target:
        entity_id: 
          - media_player.owntone_output_kitchen_homepod
          - media_player.owntone_output_kitchen_right
  device_class: speaker
  unique_id: kitchen_speakers