- platform: androidtv
  name: Living Room Fire TV Stick
  host: !secret living_room_fire_tv
- platform: universal
  name: Living Room TV Control
  children:
    - media_player.living_room_fire_tv_stick
    - media_player.living_room_denon
  commands:
    turn_on:
      service: switch.turn_on
      target:
        entity_id: switch.living_room_tv
    turn_off:
      service: switch.turn_off
      target:
        entity_id: switch.living_room_tv
    volume_up:
      service: media_player.volume_up
      target:
        entity_id: media_player.living_room_denon
    volume_down:
      service: media_player.volume_down
      target:
        entity_id: media_player.living_room_denon
    volume_mute:
      service: media_player.volume_mute
      target:
        entity_id: media_player.living_room_denon
    media_play:
      service: media_player.media_play
      target:
        entity_id: media_player.living_room_fire_tv_stick
    media_pause:
      service: media_player.media_pause
      target:
        entity_id: media_player.living_room_fire_tv_stick
    media_previous_track:
      service: media_player.media_previous_track
      target:
        entity_id: media_player.living_room_fire_tv_stick
    media_next_track:
      service: media_player.media_next_track
      target:
        entity_id: media_player.living_room_fire_tv_stick
    select_source:
      service: media_player.select_source
      target:
        entity_id: media_player.living_room_fire_tv_stick
      data:
        source: "{{ source }}"
    volume_set:
      service: media_player.volume_set
      target:
        entity_id: media_player.living_room_denon
      data:
        volume_level: "{{ volume_level }}"
  attributes:
    is_volume_muted: media_player.living_room_denon|is_volume_muted
    state: switch.living_room_tv
    volume_level: media_player.living_room_denon|volume_level
    source: media_player.living_room_fire_tv_stick|source
    source_list: media_player.living_room_fire_tv_stick|source_list
  device_class: tv