- platform: androidtv
  name: Living Room Fire TV Stick
  host: !secret living_room_fire_tv
#  get_sources: false
  apps: 
    "com.wolf.firelauncher": "Home"
    "com.hulu.plus": "Hulu"
    "com.stealth.stealthiptvbox": "Stealth"
    "com.netflix.ninja": "Netflix"
    "com.google.android.youtube.tv": "YouTube"
    "com.amazon.avod": "Prime Video"
    "com.disney.disneyplus": "Disney+"
- platform: universal
  name: Living Room TV
  children:
    - media_player.living_room_fire_tv_stick
  commands:
    turn_on:
      service: switch.turn_on
      target:
        entity_id: switch.living_room_tv
    turn_off:
      service: switch.turn_off
      target:
        entity_id: switch.living_room_tv
    volume_up:
      service: media_player.volume_set
      data:
        volume_level: "{{ states.media_player.living_room_denon.attributes.volume_level + 0.01}}"
      target:
        entity_id: media_player.living_room_denon
    volume_down:
      service: media_player.volume_set
      data:
        volume_level: "{{ states.media_player.living_room_denon.attributes.volume_level - 0.01}}"
      target:
        entity_id: media_player.living_room_denon
    volume_mute:
      service: media_player.volume_mute
      target:
        entity_id: media_player.living_room_denon
    media_play:
      service: media_player.media_play
      target:
        entity_id: media_player.living_room_fire_tv_stick
    media_pause:
      service: media_player.media_pause
      target:
        entity_id: media_player.living_room_fire_tv_stick
    media_previous_track:
      service: media_player.media_previous_track
      target:
        entity_id: media_player.living_room_fire_tv_stick
    media_next_track:
      service: media_player.media_next_track
      target:
        entity_id: media_player.living_room_fire_tv_stick
    select_source:
      service: input_select.select_option
      data_template:
        entity_id: input_select.living_room_tv_sources
        option: '{{ source }}'
    volume_set:
      service: media_player.volume_set
      target:
        entity_id: media_player.living_room_denon
      data:
        volume_level: "{{ volume_level }}"
  attributes:
    is_volume_muted: media_player.living_room_denon|is_volume_muted
    state: switch.living_room_tv
    volume_level: media_player.living_room_denon|volume_level
    source: media_player.living_room_fire_tv_stick|source
    source_list: input_select.living_room_tv_sources|options
  device_class: tv