binary_sensor:
    - state_topic: "FP"
      name: "Front Porch Motion"
      payload_on: "on"
      off_delay: 600000
      device_class: motion
    - state_topic: "backyard"
      name: "Backyard Motion"
      payload_on: "on"
      off_delay: 600000
      device_class: motion
sensor:
  - name: "LoRa_Code"
    state_topic: "LoRa-Gateway/Code"

  - name: "LoRa_RSSI"
    state_topic: "LoRa-Gateway/RSSI"