binary_sensor:
    - state_topic: "FP"
      name: "Front Porch Motion"
      payload_on: "on"
      off_delay: 600000
      device_class: motion
    - state_topic: "backyard"
      name: "Backyard Motion"
      payload_on: "on"
      off_delay: 600000
      device_class: motion