- platform: time_date
  display_options:
    - 'time'
    - 'date'
    - 'date_time'
    - 'date_time_utc'
    - 'date_time_iso'
    - 'time_date'
    - 'time_utc'
    - 'beat'

# WLED
- platform: rest
  name: WLED State
  resource: http://192.168.1.57/win
  json_attributes_path: "$.vs"
  scan_interval: 15
  json_attributes:
    - "ac"
    - "ps"