- platform: template
  sensors:
    bed_motion_battery:
      friendly_name: 'Bed Motion Battery'
      value_template: '{{ state_attr("binary_sensor.wyzemotion","battery_level") }}'
      unit_of_measurement: '%'
      device_class: battery
    bedroom_door_battery:
      friendly_name: 'Bedroom Door Sensor Battery'
      value_template: '{{ state_attr("binary_sensor.bedroom_door","battery_level") }}'
      unit_of_measurement: '%'
      device_class: battery
    window_sensor_battery:
      friendly_name: 'Window Sensor Battery'
      value_template: '{{ state_attr("binary_sensor.window","battery_level") }}'
      unit_of_measurement: '%'
      device_class: battery