- platform: wake_on_lan
  mac: !secret desktop
  name: Desktop
  host: !secret host
  turn_off:
    - service: button.press
      target:
        entity_id:
          - button.shutdown
- platform: command_line
  switches:
    u6_pro_led:
      friendly_name: "U6-Pro LED"
      command_on: !secret u6_pro_on
      command_off: !secret u6_pro_off
- platform: template
  switches:
    bedroomtoggle:
      value_template: "{{ is_state('light.desk_lights', 'on') }}"
      turn_on:
        - parallel:
          - service: script.morning
          - service: climate.set_hvac_mode
            data:
              hvac_mode: cool
            target:
              entity_id: climate.bedroom_ac
      turn_off:
        - parallel:
          - service: script.night
          - service: climate.turn_off
            target:
              entity_id:
                - climate.bedroom_ac
    ac:
      friendly_name: AC
      value_template: "{{ is_state('climate.bedroom_ac', 'cool') }}"
      turn_on:
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.bedroom_ac
        data:
          hvac_mode: 'cool'
      - service: climate.set_fan_mode
        data:
          fan_mode: Medium
        target:
          entity_id: climate.bedroom_ac
      - service: climate.set_temperature
        data:
          temperature: 70
        target:
          entity_id: climate.bedroom_ac
      - service: climate.set_preset_mode
        data:
          preset_mode: eco
        target:
          entity_id: climate.bedroom_ac
      - service: climate.set_swing_mode
        data:
          swing_mode: 'Off'
        target:
          entity_id: climate.bedroom_ac
      turn_off:
      - service: climate.set_fan_mode
        data:
          fan_mode: Medium
        target:
          entity_id: climate.bedroom_ac
      - service: climate.set_temperature
        data:
          temperature: 70
        target:
          entity_id: climate.bedroom_ac
      - service: climate.set_preset_mode
        data:
          preset_mode: eco
        target:
          entity_id: climate.bedroom_ac
      - service: climate.set_swing_mode
        data:
          swing_mode: 'Off'
        target:
          entity_id: climate.bedroom_ac
      - service: climate.set_hvac_mode
        target:
          entity_id: climate.bedroom_ac
        data:
          hvac_mode: 'off'
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.ac_boost
      - service: timer.cancel
        target:
          entity_id: timer.ac
    blinds:
      turn_on:
        service: cover.open_cover
        target:
          entity_id: cover.bedroom_blinds
      turn_off:
        service: cover.close_cover
        target:
          entity_id: cover.bedroom_blinds
    lock:
      friendly_name: Front Door Lock
      value_template: "{{ is_state('lock.front_door', 'locked') }}"
      turn_on:
        - service: lock.lock
          entity_id:
            - lock.front_door
      turn_off:
        - service: lock.unlock
          entity_id:
            - lock.front_door
    windows:
      friendly_name: Desktop
      value_template: "{{ states('sensor.monitor_plug_wattage')|float(0) > 6 }}"
      turn_on:
        - service: button.press
          target:
            entity_id:
              - button.on
        - delay: 13
        - service: homeassistant.update_entity
          entity_id: sensor.monitor_plug_wattage
      turn_off:
        - service: button.press
          target:
            entity_id:
              - button.off
        - delay: 20
        - service: homeassistant.update_entity
          entity_id: sensor.monitor_plug_wattage