- platform: command_line
  switches:
    u6_pro_led:
      friendly_name: "U6-Pro LED"
      command_on: !secret u6_pro_on
      command_off: !secret u6_pro_off
- platform: template
  switches:
    bedroomtoggle:
      value_template: "{{ is_state('light.desk_lights', 'on') }}"
      turn_on:
        - service: script.stuff_on
      turn_off:
        - service: script.turn_on
          target:
            entity_id:
              - script.stuff_off
    blinds:
      turn_on:
        service: cover.open_cover
        target:
          entity_id: cover.bedroom_blinds
      turn_off:
        service: cover.close_cover
        target:
          entity_id: cover.bedroom_blinds
    lock:
      friendly_name: Front Door Lock
      value_template: "{{ is_state('lock.front_door', 'locked') }}"
      turn_on:
        - service: lock.lock
          entity_id:
            - lock.front_door
      turn_off:
        - service: lock.unlock
          entity_id:
            - lock.front_door
    case_lights:
      friendly_name: Case Lights
      turn_on:
        - service: remote.send_command
          data:
            entity_id: remote.bedroom_rm4_remote
            command: 'off'
            device: case
        - service: remote.send_command
          data:
            entity_id: remote.bedroom_rm4_remote
            command: 'on'
            device: case
      turn_off:
        - service: remote.send_command
          data:
            entity_id: remote.bedroom_rm4_remote
            command: 'off'
            device: case
            num_repeats: 6
    ac:
      friendly_name: Air Conditioner
      value_template: "{{ states('sensor.ac_plug_wattage')|float(0) > 6 }}"
      turn_on:
        - condition: state
          entity_id: switch.ac
          state: 'off'
        - service: remote.send_command
          data:
            entity_id: remote.bedroom_rm4_remote
            command: power
            device: ac
        - delay: 4
        - service: homeassistant.update_entity
          entity_id: sensor.ac_plug_wattage
      turn_off:
        - condition: state
          entity_id: switch.ac
          state: 'on'
        - service: remote.send_command
          data:
            entity_id: remote.bedroom_rm4_remote
            command: power
            device: ac
        - service: timer.cancel
          target:
            entity_id: timer.ac
        - delay: 8
        - service: homeassistant.update_entity
          entity_id: sensor.ac_plug_wattage
    windows:
      friendly_name: Desktop
      value_template: "{{ states('sensor.monitor_plug_wattage')|float(0) > 6 }}"
      turn_on:
        - service: wake_on_lan.send_magic_packet
          data:
            mac: !secret desktop
        - service: button.press
          target:
            entity_id:
              - button.on
        - delay: 13
        - service: homeassistant.update_entity
          entity_id: sensor.monitor_plug_wattage
      turn_off:
        - service: button.press
          target:
            entity_id:
              - button.off
        - delay: 20
        - service: homeassistant.update_entity
          entity_id: sensor.monitor_plug_wattage