- platform: command_line
  switches:
    u6_lite_led:
      friendly_name: "U6-Lite LED"
      command_on: !secret u6_on
      command_off: !secret u6_off
    u6_pro_led:
      friendly_name: "U6-Pro LED"
      command_on: !secret u6_pro_on
      command_off: !secret u6_pro_off
- platform: template
  switches:
    bedroomtoggle:
      value_template: "{{ is_state('light.desk_lights', 'on') }}"
      turn_on:
        - service: script.stuff_on
      turn_off:
        - service: script.turn_on
          target:
            entity_id:
              - script.stuff_off
              - script.ac_off
    lock:
      friendly_name: Front Door Lock
      value_template: "{{ is_state('lock.front_door', 'locked') }}"
      turn_on:
        - service: lock.lock
          entity_id:
            - lock.front_door
      turn_off:
        - service: lock.unlock
          entity_id:
            - lock.front_door
    ac:
      friendly_name: Air Conditioner
      value_template: "{{ states('sensor.ac_plug_wattage')|float(default=0) > 7 }}"
      turn_on:
        - service: remote.send_command
          data:
            entity_id: remote.bedroom_rm4_remote
            command: power
            device: ac
        - delay: 4
        - service: homeassistant.update_entity
          entity_id: sensor.ac_plug_wattage
      turn_off:
        - service: remote.send_command
          data:
            entity_id: remote.bedroom_rm4_remote
            command: power
            device: ac
        - delay: 8
        - service: homeassistant.update_entity
          entity_id: sensor.ac_plug_wattage
    windows:
      friendly_name: Desktop
      value_template: "{{ states('sensor.monitor_plug_wattage')|float(default=0) > 6 }}"
      turn_on:
        - service: mqtt.publish
          data:
            topic: "iotlink/workgroup/desktop-pc/commands/displays/on"
            payload: ""  
        - service: mqtt.publish
          data:
            topic: "iotlink/workgroup/desktop-pc/commands/run"
            payload: '{"command": "C:\\Windows\\explorer.exe", "path": "C:\\Windows\\", "args": "C:\\Homebridge\\stuffonsilent.lnk", "user": "", "visible": "false", "fallback": "true"}'
        - delay: 13
        - service: homeassistant.update_entity
          entity_id: sensor.monitor_plug_wattage
      turn_off:
        - service: mqtt.publish
          data:
            topic: "iotlink/workgroup/desktop-pc/commands/run"
            payload: '{"command": "C:\\Windows\\explorer.exe", "path": "C:\\Windows\\", "args": "C:\\Homebridge\\offsilent.lnk", "user": "", "visible": "false", "fallback": "true"}'
        - delay: 20
        - service: homeassistant.update_entity
          entity_id: sensor.monitor_plug_wattage
    living_room_tv:
      friendly_name: Living Room TV
      value_template: "{{ is_state('media_player.living_room_denon', 'playing') or is_state('media_player.living_room_denon', 'on')}}"
      turn_on:
        - service: remote.send_command
          data:
            entity_id: remote.living_room_remote
            command: turn on
            device: vizio
        - service: media_player.turn_on
          data:
            entity_id: media_player.living_room_denon
        - delay: 4
      turn_off:
        - service: remote.send_command
          data:
            entity_id: remote.living_room_remote
            command: turn off
            device: vizio
        - service: media_player.turn_off
          data:
            entity_id: media_player.living_room_denon