- platform: rest
  resource: http://192.168.1.57/json/state
  name: WLED
  body_on: '{"on":true}'
  body_off: '{"on":false}'
  is_on_template: "{{ value_json.on }}"
  unique_id: wled
  method: patch
  scan_interval: 5
- platform: rest
  resource: http://192.168.1.193/json/state
  name: Govee
  body_on: '{"on":true}'
  body_off: '{"on":false}'
  is_on_template: "{{ value_json.on }}"
  scan_interval: 5
  method: patch
  unique_id: govee
- platform: rest
  resource: http://192.168.1.132/json/state
  name: Bed
  body_on: '{"on":true}'
  body_off: '{"on":false}'
  is_on_template: "{{ value_json.on }}"
  scan_interval: 5
  method: patch
  unique_id: bed
- platform: rest
  resource: http://192.168.1.180/json/state
  name: Rope
  body_on: '{"on":true}'
  body_off: '{"on":false}'
  is_on_template: "{{ value_json.on }}"
  scan_interval: 5
  method: patch
  unique_id: rope
- platform: rest
  resource: http://192.168.1.221/json/state
  name: Lamp 1
  body_on: '{"on":true}'
  body_off: '{"on":false}'
  is_on_template: "{{ value_json.on }}"
  scan_interval: 5
  method: patch
  unique_id: lamp1
- platform: rest
  resource: http://192.168.1.197/json/state
  name: Lamp 2
  body_on: '{"on":true}'
  body_off: '{"on":false}'
  is_on_template: "{{ value_json.on }}"
  scan_interval: 5
  method: patch
  unique_id: lamp2
- platform: template
  switches:
    # case_rgb:
    #   unique_id: case_rgb
    #   friendly_name: "Case RGB"
    #   turn_on:
    #     - service: remote.send_command
    #       data:
    #         device: case
    #         command: "on"
    #       target:
    #         entity_id: remote.broadlink
    #   turn_off:
    #     - service: remote.send_command
    #       data:
    #         device: case
    #         command: "off"
    #         num_repeats: 5
    #         delay_secs: 0.4
    #       target:
    #         entity_id: remote.broadlink
    fan_hold:
      unique_id: fan_hold
      friendly_name: Fan Hold
      value_template: "{{ is_state_attr('climate.home', 'fan_mode', 'on') }}"
      turn_on:
        - service: climate.set_fan_mode
          target:
            entity_id: climate.home
          data:
            fan_mode: 'on'
      turn_off:
        - service: climate.set_fan_mode
          target: 
            entity_id: climate.home
          data:
            fan_mode: auto
    ac_boost:
      unique_id: ac_boost
      friendly_name: "AC Boost"
      value_template: "{{ is_state('input_boolean.ac_boost', 'on') }}"
      turn_on:
        - service: input_boolean.turn_on
          target:
              entity_id: input_boolean.ac_boost
      turn_off:
        - service: input_boolean.turn_off
          target:
              entity_id: input_boolean.ac_boost
    privacy:
      friendly_name: "Privacy"
      unique_id: privacy
      value_template: "{{ is_state('input_boolean.privacy', 'on') }}"
      turn_on:
        - service: input_boolean.turn_on
          target:
              entity_id: input_boolean.privacy
      turn_off:
        - service: input_boolean.turn_off
          target:
              entity_id: input_boolean.privacy
    bedroomtoggle:
      unique_id: bedroom_toggle
      value_template: "{{ is_state('light.bedroom_lights', 'on') 
                      or is_state('light.wled', 'on')
                      or is_state('light.bed', 'on')
                      or is_state('light.govee', 'on')}}"
      turn_on:
        - parallel:
          - service: script.morning
          - service: switch.turn_on
            target:
              entity_id: switch.light_switch_relay
          # - service: climate.set_hvac_mode
          #   data:
          #     hvac_mode: cool
          #   target:
          #     entity_id: climate.bedroom_ac
      turn_off:
        - parallel:
          - service: script.night
          - service: media_player.turn_off
            target:
              entity_id:
                - media_player.owntone_output_anthony_s_desk
                - media_player.owntone_output_anthony_s_nightstand
          - service: climate.turn_off
            target:
              entity_id:
                - climate.bedroom_ac
    ac:
      friendly_name: AC
      unique_id: ac
      value_template: "{{ is_state('climate.bedroom_ac', 'cool') }}"
      turn_on:
      - service: climate.set_hvac_mode
        data:
          hvac_mode: cool
        target:
          entity_id: climate.bedroom_ac
      - service: climate.set_preset_mode
        data:
          preset_mode: none
        target:
          entity_id: climate.bedroom_ac
      - delay:
          seconds: 2
      - service: climate.set_preset_mode
        data:
          preset_mode: none
        target:
          entity_id: climate.bedroom_ac
      turn_off:
      - service: climate.turn_off
        target:
          entity_id: climate.bedroom_ac
      - service: input_boolean.turn_off
        target:
          entity_id: input_boolean.ac_boost
      - service: timer.cancel
        target:
          entity_id: timer.ac
      - delay: 
          seconds: 1
      - service: climate.turn_off
        target:
          entity_id: climate.bedroom_ac
      - service: switch.turn_off
        target:
          entity_id: switch.ac_boost
    lrtv:
      unique_id: lrtv
      friendly_name: Living Room TV
      value_template: "{{ not is_state('media_player.living_room_denon', 'off') }}"
      turn_on:
        - service: media_player.turn_on
          target:
            entity_id:
              - media_player.living_room_tv
              - media_player.living_room_denon
      turn_off:
        - service: media_player.turn_off
          target:
            entity_id:
              - media_player.living_room_tv
              - media_player.living_room_denon
              - media_player.owntone_output_living_room_tv
    samsungtv:
      unique_id: samsung_tv
      friendly_name: Samsung TV
      turn_on:
        - service: remote.send_command
          data:
            command: "on"
            device: samsung
            hold_secs: 2
          target:
            entity_id: remote.wi_fi_universal_remote
      turn_off:
        - service: remote.send_command
          data:
            command: "off"
            device: samsung
            hold_secs: 2
          target:
            entity_id: remote.wi_fi_universal_remote
    fronttv:
      unique_id: fronttv
      friendly_name: Front TV
      value_template: "{{ states('media_player.hisense_tv') }}"
      turn_on:
        - service: switch.turn_on
          target:
            entity_id:
              - switch.hisense_tv
      turn_off:
        - condition: state
          entity_id: switch.fronttv
          state: "on"
        - service: media_player.turn_off
          target:
            entity_id:
              - media_player.owntone_output_front
        - service: switch.turn_off
          target:
            entity_id:
              - switch.hisense_tv
    brtv:
      unique_id: brtv
      friendly_name: Bedroom TV
      value_template: "{{ not is_state('media_player.front', 'standby') }}"
      turn_on:
        - service: media_player.turn_on
          target:
            entity_id:
              - media_player.front
      turn_off:
        - service: media_player.turn_off
          target:
            entity_id:
              - media_player.front
    acfanhigh:
      unique_id: acfanhigh
      friendly_name: AC Fan High
      value_template: "{{ states('climate.bedroom_ac') in ['cool', 'fan_only'] and ((is_state_attr('climate.bedroom_ac', 'fan_mode', 'high') or is_state('input_boolean.ac_boost', 'on'))) }}"
      turn_on:
        - service: switch.turn_on
          target:
            entity_id: switch.ac
        - service: climate.set_fan_mode
          data:
            fan_mode: high
          target:
            entity_id: climate.bedroom_ac
        - delay:
            seconds: 3
        - service: climate.set_fan_mode
          data:
            fan_mode: high
          target:
            entity_id: climate.bedroom_ac
        - delay:
            seconds: 3
        - service: climate.set_fan_mode
          data:
            fan_mode: high
          target:
            entity_id: climate.bedroom_ac
        - delay:
            seconds: 3
        - service: climate.set_fan_mode
          data:
            fan_mode: high
          target:
            entity_id: climate.bedroom_ac
      turn_off:
        - service: climate.set_fan_mode
          data:
              fan_mode: auto
          target:
            entity_id: climate.bedroom_ac
    guesttv:
      unique_id: guesttv
      friendly_name: Guest TV
      value_template: "{{ is_state('binary_sensor.guest_bedroom_tv_in_use', 'on') }} "
      turn_on:
        - service: media_player.turn_on
          target:
            entity_id:
              - media_player.guest_tv
      turn_off:
        - service: media_player.turn_off
          target:
            entity_id:
              - media_player.guest_tv
    mastertv:
      unique_id: mastertv
      friendly_name: Master TV
      value_template: "{{ not is_state('media_player.master_bedroom_tv', 'standby') }}"
      turn_on:
        - service: media_player.turn_on
          target:
            entity_id:
              - media_player.master_bedroom_tv
      turn_off:
        - service: media_player.turn_off
          target:
            entity_id:
              - media_player.master_bedroom_tv
              - media_player.owntone_output_master_bedroom_tv
    airport_express:
      unique_id: airport_express
      friendly_name: AirPort Express
      value_template: "{{ is_state('light.caseta_lamp_dimmer', 'on') }}"
      turn_on:
        - service: light.turn_on
          data:
            brightness_pct: 100
          target:
            entity_id:
              - light.caseta_lamp_dimmer
      turn_off:
        - service: light.turn_off
          target:
            entity_id:
              - light.caseta_lamp_dimmer
    desktop:
      unique_id: desktop
      friendly_name: Desktop
      value_template: "{{ states('binary_sensor.desktop_power') }}"
      turn_on:
        - service: wake_on_lan.send_magic_packet
          data:
            mac: !secret desktop
        - service: switch.turn_on
          target: 
            entity_id: switch.sonoff_s31_lite_zb_switch_2
      turn_off:
        - service: button.press
          target:
            entity_id:
              - button.shutdown
        - service: switch.turn_off
          target: 
            entity_id: switch.sonoff_s31_lite_zb_switch_2