- platform: rest
  resource: http://192.168.1.57/json/state
  name: WLED Main Power
  body_on: '{"on":true}'
  body_off: '{"on":false}'
  is_on_template: "{{ value_json.on }}"
  unique_id: wled_main_power
  method: patch
  scan_interval: 5
- platform: rest
  resource: http://192.168.1.57/json/state/seg
  name: WLED
  body_on: '{"seg": [{"id": 0, "on": true}]}'
  body_off: '{"seg": [{"id": 0, "on": false}]}'
  is_on_template: "{{ value_json.seg[0].on }}"
  unique_id: wled
  method: patch
  scan_interval: 5
- platform: rest
  resource: http://192.168.1.57/json/state/seg
  name: Closet Lights
  body_on: '{"seg": [{"id": 1, "on": true}]}'
  body_off: '{"seg": [{"id": 1, "on": false}]}'
  is_on_template: "{{ value_json.seg[1].on }}"
  unique_id: closet_lights
  method: patch
  scan_interval: 5
- platform: rest
  resource: http://192.168.1.193/json/state
  name: Govee
  body_on: '{"on":true}'
  body_off: '{"on":false}'
  is_on_template: "{{ value_json.on }}"
  scan_interval: 5
  method: patch
  unique_id: govee
- platform: rest
  resource: http://192.168.1.132/json/state
  name: Bed
  body_on: '{"on":true}'
  body_off: '{"on":false}'
  is_on_template: "{{ value_json.on }}"
  scan_interval: 5
  method: patch
  unique_id: bed
- platform: rest
  resource: http://192.168.1.104/json/state
  name: Rope
  body_on: '{"on":true}'
  body_off: '{"on":false}'
  is_on_template: "{{ value_json.on }}"
  scan_interval: 5
  method: patch
  unique_id: rope
- platform: rest
  resource: http://192.168.1.78/json/state
  name: Cube
  body_on: '{"on":true}'
  body_off: '{"on":false}'
  is_on_template: "{{ value_json.on }}"
  scan_interval: 5
  method: patch
  unique_id: cube
- platform: rest
  resource: http://192.168.1.177/json/state
  name: Block
  body_on: '{"on":true}'
  body_off: '{"on":false}'
  is_on_template: "{{ value_json.on }}"
  scan_interval: 5
  method: patch
  unique_id: block
- platform: rest
  resource: http://192.168.1.105:3000/api/deviceStatus
  name: Eight Sleep
  body_on: '{ "left": { "targetTemperatureF": 55, "isOn": true } }'
  body_off: '{ "left": { "isOn": false } }'
  is_on_template: "{{ value_json.left.isOn }}"
  unique_id: eightsleep
  headers:
    Content-Type: application/json
  method: post
  scan_interval: 5
- platform: rest
  resource: http://192.168.1.105:3000/api/deviceStatus
  name: Eight Sleep Keep Temp
  body_on: '{ "left": { "isOn": true } }'
  body_off: '{ "left": { "isOn": false } }'
  is_on_template: "{{ value_json.left.isOn }}"
  unique_id: eightsleepkeeptemp
  headers:
    Content-Type: application/json
  method: post
  scan_interval: 5
- platform: template
  switches:
    # case_rgb:
    #   unique_id: case_rgb
    #   friendly_name: "Case RGB"
    #   turn_on:
    #     - service: remote.send_command
    #       data:
    #         device: case
    #         command: "on"
    #       target:
    #         entity_id: remote.broadlink
    #   turn_off:
    #     - service: remote.send_command
    #       data:
    #         device: case
    #         command: "off"
    #         num_repeats: 5
    #         delay_secs: 0.4
    #       target:
    #         entity_id: remote.broadlink
    fan_hold:
      unique_id: fan_hold
      friendly_name: Fan Hold
      value_template: "{{ is_state_attr('climate.home', 'fan_mode', 'on') }}"
      turn_on:
        - service: climate.set_fan_mode
          target:
            entity_id: climate.home
          data:
            fan_mode: 'on'
      turn_off:
        - service: climate.set_fan_mode
          target: 
            entity_id: climate.home
          data:
            fan_mode: auto
    ac_boost:
      unique_id: ac_boost
      friendly_name: "AC Boost"
      #value_template: "{{ is_state('switch.ac_boost', 'on') }}"
      turn_on:
        - service: switch.turn_on
          target:
              entity_id: switch.ac_boost
      turn_off:
        - service: switch.turn_off
          target:
              entity_id: switch.ac_boost
    bedroomtoggle:
      unique_id: bedroom_toggle
      value_template: "{{ is_state('light.bedroom_lights', 'on') 
                      or is_state('light.wled', 'on')
                      or is_state('light.bed', 'on')
                      or is_state('light.govee', 'on')}}"
      turn_on:
        - parallel:
          - service: script.morning
          - service: switch.turn_on
            target:
              entity_id: switch.light_switch_relay
          # - service: climate.set_hvac_mode
          #   data:
          #     hvac_mode: cool
          #   target:
          #     entity_id: climate.bedroom_ac
      turn_off:
        - parallel:
          - service: script.night
          - service: media_player.turn_off
            target:
              entity_id:
                - media_player.owntone_output_anthony_s_desk
                - media_player.owntone_output_anthony_s_nightstand
          - service: climate.turn_off
            target:
              entity_id:
                - climate.bedroom_ac
    ac:
      friendly_name: AC
      unique_id: ac
      value_template: "{{ is_state('climate.bedroom_ac', 'cool') }}"
      turn_on:
      - service: climate.set_hvac_mode
        data:
          hvac_mode: cool
        target:
          entity_id: climate.bedroom_ac
      - service: climate.set_preset_mode
        data:
          preset_mode: none
        target:
          entity_id: climate.bedroom_ac
      - delay:
          seconds: 2
      - service: climate.set_preset_mode
        data:
          preset_mode: none
        target:
          entity_id: climate.bedroom_ac
      turn_off:
      - service: climate.turn_off
        target:
          entity_id: climate.bedroom_ac
      - service: switch.turn_off
        target:
          entity_id: switch.ac_boost
      - service: timer.cancel
        target:
          entity_id: timer.ac
      - delay: 
          seconds: 1
      - service: climate.turn_off
        target:
          entity_id: climate.bedroom_ac
      - service: switch.turn_off
        target:
          entity_id: switch.ac_boost
    acfanhigh:
      unique_id: acfanhigh
      friendly_name: AC Fan High
      value_template: "{{ states('climate.bedroom_ac') in ['cool', 'fan_only'] and ((is_state_attr('climate.bedroom_ac', 'fan_mode', 'high') or is_state('switch.ac_boost', 'on'))) }}"
      turn_on:
        - service: switch.turn_on
          target:
            entity_id: switch.ac
        - service: climate.set_fan_mode
          data:
            fan_mode: high
          target:
            entity_id: climate.bedroom_ac
        - delay:
            seconds: 3
        - service: climate.set_fan_mode
          data:
            fan_mode: high
          target:
            entity_id: climate.bedroom_ac
        - delay:
            seconds: 3
        - service: climate.set_fan_mode
          data:
            fan_mode: high
          target:
            entity_id: climate.bedroom_ac
        - delay:
            seconds: 3
        - service: climate.set_fan_mode
          data:
            fan_mode: high
          target:
            entity_id: climate.bedroom_ac
      turn_off:
        - service: climate.set_fan_mode
          data:
              fan_mode: auto
          target:
            entity_id: climate.bedroom_ac
    guesttv:
      unique_id: guesttv
      friendly_name: Samsung TV
      value_template: "{{ is_state('switch.samsung_tv', 'on') }} "
      turn_on:
        - service: switch.turn_on
          target:
            entity_id:
              - switch.samsung_tv
      turn_off:
        - service: switch.turn_off
          target:
            entity_id:
              - switch.samsung_tv
    airport_express:
      unique_id: airport_express
      friendly_name: AirPort Express
      value_template: "{{ is_state('light.caseta_lamp_dimmer', 'on') }}"
      turn_on:
        - service: light.turn_on
          data:
            brightness_pct: 100
          target:
            entity_id:
              - light.caseta_lamp_dimmer
      turn_off:
        - service: light.turn_off
          target:
            entity_id:
              - light.caseta_lamp_dimmer
    caseta_lamp_plug_2:
      unique_id: caseta_lamp_plug_2
      friendly_name: Caseta Lamp Plug 2
      value_template: "{{ is_state('light.caseta_lamp_plug_2', 'on') }}"
      turn_on:
        - service: light.turn_on
          data:
            brightness_pct: 100
          target:
            entity_id:
              - light.caseta_lamp_plug_2
      turn_off:
        - service: light.turn_off
          target:
            entity_id:
              - light.caseta_lamp_plug_2
    caseta_lamp_plug_3:
      unique_id: caseta_lamp_plug_3
      friendly_name: Caseta Lamp Plug 3
      value_template: "{{ is_state('light.dana_s_bedroom_north_holiday_lights', 'on') }}"
      turn_on:
        - service: light.turn_on
          data:
            brightness_pct: 100
          target:
            entity_id:
              - light.dana_s_bedroom_north_holiday_lights
      turn_off:
        - service: light.turn_off
          target:
            entity_id:
              - light.dana_s_bedroom_north_holiday_lights
    caseta_lamp_plug_4:
      unique_id: caseta_lamp_plug_4
      friendly_name: Caseta Lamp Plug 4
      value_template: "{{ is_state('light.dana_s_bedroom_south_holiday_lights', 'on') }}"
      turn_on:
        - service: light.turn_on
          data:
            brightness_pct: 100
          target:
            entity_id:
              - light.dana_s_bedroom_south_holiday_lights
      turn_off:
        - service: light.turn_off
          target:
            entity_id:
              - light.dana_s_bedroom_south_holiday_lights
    caseta_lamp_plug_5:
      unique_id: caseta_lamp_plug_5
      friendly_name: Caseta Lamp Plug 5
      value_template: "{{ is_state('light.dana_s_bedroom_soundbar_airport', 'on') }}"
      turn_on:
        - service: light.turn_on
          data:
            brightness_pct: 100
          target:
            entity_id:
              - light.dana_s_bedroom_soundbar_airport
      turn_off:
        - service: light.turn_off
          target:
            entity_id:
              - light.dana_s_bedroom_soundbar_airport
    caseta_lamp_plug_6:
      unique_id: caseta_lamp_plug_6
      friendly_name: Caseta Lamp Plug 6
      value_template: "{{ is_state('light.katchy', 'on') }}"
      turn_on:
        - service: light.turn_on
          data:
            brightness_pct: 100
          target:
            entity_id:
              - light.katchy
      turn_off:
        - service: light.turn_off
          target:
            entity_id:
              - light.katchy
    caseta_lamp_plug_7:
      unique_id: caseta_lamp_plug_7
      friendly_name: Caseta Lamp Plug 7
      value_template: "{{ is_state('light.anthony_s_bedroom_usb_hub', 'on') }}"
      turn_on:
        - service: light.turn_on
          data:
            brightness_pct: 100
          target:
            entity_id:
              - light.anthony_s_bedroom_usb_hub
      turn_off:
        - service: light.turn_off
          target:
            entity_id:
              - light.anthony_s_bedroom_usb_hub
    desktop:
      unique_id: desktop
      friendly_name: Desktop
      value_template: "{{ not is_state('button.desktop_pc_satellite_shutdown', 'unavailable') }} "
      turn_on:
        - service: switch.turn_on
          target: 
            entity_id: 
              - switch.usb_hub
        - service: wake_on_lan.send_magic_packet
          data:
            mac: !secret desktop
        - service: wake_on_lan.send_magic_packet
          data:
            mac: !secret desktop6
        - service: wake_on_lan.send_magic_packet
          data:
            mac: !secret desktop2
        - service: wake_on_lan.send_magic_packet
          data:
            mac: !secret desktop3
        - service: wake_on_lan.send_magic_packet
          data:
            mac: !secret desktop4
        - service: wake_on_lan.send_magic_packet
          data:
            mac: !secret desktop5
      turn_off:
        - service: button.press
          target:
            entity_id:
              - button.desktop_pc_satellite_shutdown