- platform: template
  switches:
    bedroomtoggle:
      value_template: >
        {{ is_state('light.desk_lights', 'on') }}
      turn_on:
        - service: script.stuff_on
      turn_off:
        - service: script.stuff_off
    vizio_tv:
      friendly_name: Bedroom TV
      value_template: "{{ states('sensor.tv_plug_wattage')|float > 5 }}"
      turn_on:
        - service: remote.send_command
          data:
            entity_id: remote.bedroom_rm4_remote
            command: turn on
            device: vizio
        - delay: 8
        - service: homeassistant.update_entity
          entity_id: sensor.tv_plug_wattage
      turn_off:
        - service: remote.send_command
          data:
            entity_id: remote.bedroom_rm4_remote
            command: turn off
            device: vizio
        - delay: 8
        - service: homeassistant.update_entity
          entity_id: sensor.tv_plug_wattage
    ac:
      friendly_name: Air Conditioner
      value_template: "{{ states('sensor.ac_plug_wattage')|float > 7 }}"
      turn_on:
        - service: remote.send_command
          data:
            entity_id: remote.bedroom_rm4_remote
            command: power
            device: ac
        - delay: 4
        - service: homeassistant.update_entity
          entity_id: sensor.ac_plug_wattage
      turn_off:
        - service: remote.send_command
          data:
            entity_id: remote.bedroom_rm4_remote
            command: power
            device: ac
        - delay: 8
        - service: homeassistant.update_entity
          entity_id: sensor.ac_plug_wattage
    windows:
      friendly_name: Windows
      value_template: "{{ states('sensor.monitor_plug_wattage')|float > 3 }}"
      turn_on:
        - service: shell_command.pc_on
        - delay: 11
        - service: homeassistant.update_entity
          entity_id: sensor.monitor_plug_wattage
      turn_off:
        - service: shell_command.pc_off
        - delay: 18
        - service: homeassistant.update_entity
          entity_id: sensor.monitor_plug_wattage
    living_room_vizio:
      friendly_name: Living Room Vizio
      turn_on:
        - service: remote.send_command
          data:
            entity_id: remote.living_room_remote
            command: turn on
            device: vizio
      turn_off:
        - service: remote.send_command
          data:
            entity_id: remote.living_room_remote
            command: turn off
            device: vizio