esphome:
  name: bedscale
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret ssid
  password: !secret password
  fast_connect: on
  ap: {}

captive_portal:
logger:
api:
ota:

sensor:
  - platform: hx711
    gain: 128
#    name: "Bed Weight"
    id: bed_weight
    dout_pin: D4
    clk_pin: RX
    filters:
#      - delta: 3000
      - calibrate_linear:
          - 392000 -> 0
          - 428000 -> 280
#      - sliding_window_moving_average:
#          window_size: 5
#          send_every: 3
      - lambda: |-
          if (x >= 0) return x;
          else return {};
      - lambda: |-
          if (x <= 500) return x;
          else return {};
    update_interval: 350ms
    unit_of_measurement: lbs
    accuracy_decimals: 0
    
binary_sensor:
  - platform: template
    name: "Bed Occupancy"
    device_class: occupancy
    lambda: |-
      if (id(bed_weight).state > 180) {
        return true;
      } else {
        return false;
      }      