#external_components:
#  source: github://rednblkx/HAP-ESPHome@main
#  refresh: 0s

esphome:
  name: carprox

esp32:
  board: mhetesp32minikit
#  flash_size: 8MB
#  framework:
#    type: esp-idf
#    version: 5.2.3
#    platform_version: 6.9.0
#    sdkconfig_options:
#      CONFIG_COMPILER_OPTIMIZATION_SIZE: y
#      CONFIG_LWIP_MAX_SOCKETS: "16"
#      CONFIG_MBEDTLS_HKDF_C: y
#      CONFIG_ESPTOOLPY_FLASHSIZE_8MB: y
#      CONFIG_COMPILER_OPTIMIZATION_PERF: n
#      CONFIG_COMPILER_OPTIMIZATION_CHECKS_SILENT: y
#      CONFIG_LOG_MAXIMUM_LEVEL_ERROR: y
#      CONFIG_LOG_MAXIMUM_LEVEL_INFO: n
#      CONFIG_ETH_USE_SPI_ETHERNET: n
#      CONFIG_LWIP_PPP_SUPPORT: n
#      CONFIG_COMPILER_OPTIMIZATION_ASSERTION_LEVEL: Silent
#      CONFIG_ESP_ERR_TO_NAME_LOOKUP: n
#      CONFIG_ESP32_REV_MIN_3_1: y
#      CONFIG_HAL_ASSERTION_DISABLE: y
#      CONFIG_LWIP_IPV6: n
      #CONFIG_LWIP_IPV4: n
#      CONFIG_NEWLIB_NANO_FORMAT: y
#      CONFIG_ESP_WIFI_ENABLE_WPA3_SAE: n
#      CONFIG_ESP_WIFI_SOFTAP_SUPPORT: n
#      CONFIG_ESP_WIFI_ENTERPRISE_SUPPORT: n

# Enable logging
logger:

esp32_ble_tracker:
  scan_parameters: 
    interval: 320ms
    window: 30ms
    active: false
    duration: 1s

binary_sensor:
    # Presence based on Identity Resolving Key (IRK)
  - platform: ble_presence
    irk: 8747d48a6dbe4ddc36df52cc7bd2ab2a
    id: iphone
    min_rssi: -60dB
#    on_release:
#      then:
#        - button.press: button_lock

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  reboot_timeout: 0s
  enable_on_boot: false
    
#lock:
#  - platform: template
#    id: car
#    optimistic: True
#    lock_action:
#      - button.press: button_lock
#    unlock_action:
#      - button.press: button_unlock

#output:
#  - platform: gpio
#    pin: 
#      number: GPIO47
#      inverted: True
#    id: output_unlock
#  - platform: gpio
#    pin: 
#      number: GPIO48
#      inverted: True
#    id: output_lock

#button:
#  - platform: output
#    id: button_unlock
#    output: output_unlock
#    duration: 800ms
#  - platform: output
#    id: button_lock
#    output: output_lock
#    duration: 800ms

#homekit:
#  lock:
#    - id: car
#      nfc_id: nfc_spi_module
#      on_hk_success:
#        lambda: |-
#          if (id(car).state == LOCK_STATE_LOCKED) {
#            id(car).unlock();
#          }
#          else {
#            id(car).lock();
#          }
#      hk_hw_finish: "GOLD"

#spi:
#  clk_pin: 4
#  miso_pin: 5
#  mosi_pin: 6

#pn532_spi:
#  id: nfc_spi_module
#  cs_pin: 7
#  update_interval: 100ms