<<: !include .led_base.yaml

substitutions:
  friendly_name: "Closet Lights"
  name: closetlights
  static_ip: 192.168.1.210
  red: GPIO5
  green: GPIO14
  blue: GPIO12

binary_sensor:
  - platform: homeassistant
    entity_id: binary_sensor.closet
    id: closetstate
    on_release:
      - light.turn_off: leds
  - platform: template
    id: lighton
    on_press:
      then:
        - if:
            condition: 
              binary_sensor.is_off: closetstate
            then: 
              - light.turn_off: leds
    lambda: 'return id(leds).current_values.is_on();'