esphome:
  name: ${name}

esp32:
  board: esp32dev
  framework:
    type: arduino

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16
  manual_ip:
    static_ip: ${static_ip}
    gateway: !secret gateway
    subnet: !secret subnet
    dns1: !secret dns1

logger:
api:
ota:
web_server:

sensor:
  - platform: homeassistant
    entity_id: sensor.colorloopstate
    id: hassstate

light:
  - platform: rgb
    id: leds
    name: "${friendly_name}"
    red: output_red_2
    green: output_green_2
    blue: output_blue_2
    restore_mode: RESTORE_DEFAULT_OFF
    effects:
      - random:
          name: Music
          transition_length: .1s
          update_interval: .2s
      - lambda:
          name: Color Loop
          lambda: |-
            static float state = 0;
            if (state != id(hassstate).state) {
              state = id(hassstate).state;
              auto call = id(leds).turn_on();
              call.set_transition_length(3000);
              if (state == 0) {
                call.set_rgb(0.45, 0.98, 0.39);
              } else if (state == 1) {
                call.set_rgb(0.45, 0.98, 0.93);
              } else if (state == 2) {
                call.set_rgb(0.38, 0.15, 0.96);
              } else if (state == 3) {
                call.set_rgb(0.5, 0.17, 0.96);
              } else {
                call.set_rgb(0.92, 0.2, 0.27);
              }
              call.perform();
            }

output:
  - platform: ledc
    id: output_red
    pin: ${red}
  - platform: ledc
    id: output_blue
    pin: ${green}
  - platform: ledc
    id: output_green
    pin: ${blue_2}
  - platform: ledc
    id: output_red_2
    pin: ${red_2}
  - platform: ledc
    id: output_blue_2
    pin: ${green_2}
  - platform: ledc
    id: output_green_2
    pin: ${blue}

substitutions:
  static_ip: 192.168.1.195
  red: GPIO02
  green: GPIO12
  blue: GPIO05
  red_2: GPIO14
  green_2: GPIO15
  blue_2: GPIO04
  friendly_name: "Desk Lights"
  friendly_name_2: "Closet Lights"
  name: desklights