substitutions:
  name: kauf-plug-7aacf2
packages:
  Kauf.PLF12: github://KaufHA/PLF12/kauf-plf12.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false



wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
