substitutions:
  name: kauf-rgbsw-63e843
  static_ip: 192.168.1.203
packages:
  Kauf.RGBSw: github://KaufHA/kauf-rgb-switch/kauf-rgbs.yaml

web_server:
  !remove

wifi:
  networks:
    - ssid: !secret ssid
      password: !secret password
#      bssid: 9C:05:D6:37:4A:30
  #fast_connect: on
  #power_save_mode: none
  #reboot_timeout: 5min
  #output_power: 8.5dB
  #reboot_timeout: 0s
  manual_ip:
    static_ip: ${static_ip}
    gateway: !secret gateway
    subnet: !secret subnet
    dns1: !secret dns1

