esphome:
  name: lamp1

esp32:
  board: wt32-eth01
  framework:
    type: esp-idf

#wifi:
#  ssid: !secret ssid
#  password: !secret password
#  fast_connect: on
#  enable_btm: true
#  manual_ip:
#    static_ip: ${static_ip}
#    gateway: !secret gateway
#    subnet: !secret subnet
#    dns1: !secret dns1

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16
  manual_ip:
    static_ip: ${static_ip}
    gateway: !secret gateway
    subnet: !secret subnet
    dns1: !secret dns1

substitutions:
  static_ip: 192.168.1.221
  # red: GPIO05
  # green: GPIO33
  # blue: GPIO32
  # friendly_name: "Bed Lights"

bluetooth_proxy:
  active: true
esp32_ble_tracker:
  scan_parameters:
    interval: 1100ms
    window: 1100ms

logger:
api:
ota:
  platform: esphome