esphome:
  name: midea
  platform: ESP8266
  board: esp12e

wifi:
  ssid: !secret ssid
  use_address: 192.168.1.3
  password: !secret password
  fast_connect: on
  ap: {}

captive_portal:
api:
ota:

# Disable logging over UART (required)
logger:
  baud_rate: 0

# UART settings for Midea dongle (required)
uart:
  tx_pin: 1         # hardware dependant
  rx_pin: 3         # hardware dependant
  baud_rate: 9600

# Main settings
climate:
  - platform: midea
    name: Bedroom AC            # Use a unique name.
    #period: 1200ms
    num_attempts: 5
    autoconf: true              # Autoconfigure most options.
    visual:             
      min_temperature: 16 °C # Optional. Example of visual settings override.
      temperature_step: 1 °C    # min: 0.5
    supported_modes:            # All capabilities in this section detected by autoconf.
      - FAN_ONLY                # This capability is always used.
      - COOL
      - DRY
    custom_fan_modes:
      - SILENT
      - TURBO
    outdoor_temperature:        # Optional. Outdoor temperature sensor (may display incorrect values after long inactivity).
      name: Temp