esphome:
  name: midea
  platform: ESP8266
  board: esp12e

wifi:
  ssid: !secret ssid
  password: !secret password
  fast_connect: on
  ap: {}
  manual_ip:
    static_ip: 192.168.1.3
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.250

captive_portal:
api:
ota:

# Disable logging over UART (required)
logger:
  baud_rate: 0

# UART settings for Midea dongle (required)
uart:
  tx_pin: 1         # hardware dependant
  rx_pin: 3         # hardware dependant
  baud_rate: 9600

# Main settings
climate:
  - platform: midea
    name: Bedroom AC            
    #period: 1200ms
    num_attempts: 5
    autoconf: true              
    visual:             
      min_temperature: 16 °C
      temperature_step: 1 °C    
    supported_modes:            
      - FAN_ONLY                
      - COOL
      - DRY
    custom_fan_modes:
      - SILENT
      - TURBO
    outdoor_temperature:        
      name: Temp