esphome:
  name: midea
  platform: ESP8266
  board: esp12e

wifi:
  ssid: !secret ssid
  password: !secret password
  fast_connect: on
  #output_power: 8.5dB
  manual_ip:
    static_ip: ${static_ip}
    gateway: !secret gateway
    subnet: !secret subnet
    dns1: !secret dns1
    
substitutions:
  static_ip: 192.168.1.3

captive_portal:
api:
ota:

web_server:

# Disable logging over UART (required)
logger:
  baud_rate: 0

button:
  platform: template
  name: "Display Toggle"
  on_press:
    - midea_ac.display_toggle:

switch:
  - platform: template
    name: Beeper
    icon: mdi:volume-source
    optimistic: true
    turn_on_action:
      midea_ac.beeper_on:
    turn_off_action:
      midea_ac.beeper_off:

# UART settings for Midea dongle (required)
uart:
  tx_pin: 1         # hardware dependant
  rx_pin: 3         # hardware dependant
  baud_rate: 9600

# Main settings
climate:
  - platform: midea
    name: Bedroom AC            
    #period: 1200ms
    num_attempts: 5
    autoconf: true              
    visual:             
      min_temperature: 16 °C
      temperature_step: 1 °C    
    supported_modes:            
      - FAN_ONLY                
      - COOL
      - DRY
    custom_fan_modes:
      - SILENT
      - TURBO
    outdoor_temperature:        
      name: Temp