esphome:
  name: occupancy-eth

esp32:
  board: esp32dev
  framework:
    type: arduino

#wifi:
#  ssid: !secret ssid
#  password: !secret password
#  fast_connect: on
#  manual_ip:
#    static_ip: ${static_ip}
#    gateway: !secret gateway
#    subnet: !secret subnet
#    dns1: !secret dns1

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16
  manual_ip:
    static_ip: ${static_ip}
    gateway: !secret gateway
    subnet: !secret subnet
    dns1: !secret dns1

substitutions:
  static_ip: 192.168.1.146


#captive_portal:
logger:
api:
ota:

sensor:
  - platform: hx711
    gain: 128
#    name: "Bed Weight"
    id: bed_weight
    dout_pin: GPIO2
    clk_pin: GPIO4
    filters:
      - delta: 3000
      - calibrate_linear:
          - 320000 -> 0
          - 386000 -> 285
#      - sliding_window_moving_average:
#          window_size: 5
#          send_every: 3
      - lambda: |-
          if (x >= 0) return x;
          else return {};
 #     - lambda: |-
 #         if (x <= 500) return x;
 #         else return {};
    on_value:
      - if:
          condition:
            - lambda: |-
                static float last = 0.0;
                float diff = x - last;
                last = x;
                return x < 10.0 && diff < 1.0 && diff > - 1.0;
          then:
            - lambda: 'id(constant_weight) = x;'
    update_interval: 350ms
    unit_of_measurement: lbs
    accuracy_decimals: 0
    
globals:
  - id: constant_weight
    type: float
    
binary_sensor:
  - platform: template
    name: "Bed Occupancy"
    device_class: occupancy
    lambda: |-
      if (id(bed_weight).state > 160) {
        return true;
      } else {
        return false;
      }      