esphome:
  name: roundplug2
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret ssid
  password: !secret password
  fast_connect: on
  ap: {}
  manual_ip:
    static_ip: 192.168.1.7
    gateway: !secret gateway
    subnet: !secret subnet
    dns1: !secret dns1

captive_portal:
logger:
api:
ota:

substitutions:
  name: "Dana's North Incandescent Rope"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    id: button
    on_release:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "${name}"
    pin: GPIO12
    id: relay
    restore_mode: RESTORE_DEFAULT_ON