esphome:
  name: smartstrip
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret ssid
  password: !secret password
  fast_connect: on
  manual_ip:
    static_ip: 192.168.1.35
    gateway: !secret gateway
    subnet: !secret subnet
  ap:
    ssid: "${name} Fallback Hotspot"
    password: ""

captive_portal:
logger:
api:
ota:

substitutions:
  name: "Power Strip"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
      mode: INPUT_PULLUP
      inverted: True
    id: smartstripbutton
    on_press:
      - switch.toggle: relay1
      - switch.toggle: relay2
      - switch.toggle: relay3
      - switch.toggle: relay4
      - switch.toggle: relay5
switch:
  - platform: gpio
    name: "${name} Outlet 1"
    pin: GPIO4
    inverted: yes
    id: 'relay1'
    restore_mode: ALWAYS_ON
  - platform: gpio
    name: "${name} Outlet 2"
    pin: GPIO13
    inverted: yes
    id: 'relay2'
    restore_mode: ALWAYS_ON
  - platform: gpio
    name: "${name} Outlet 3"
    pin: GPIO12
    inverted: yes
    id: 'relay3'
    restore_mode: ALWAYS_ON
  - platform: gpio
    name: "${name} Outlet 4"
    pin: GPIO14
    inverted: yes
    id: 'relay4'
    restore_mode: ALWAYS_ON
  - platform: gpio
    name: "${name} USBs"
    pin: GPIO16
    id: 'relay5'
    restore_mode: ALWAYS_ON
