esphome:
  name: smartoutlet
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret ssid
  password: !secret password
  fast_connect: on
  ap: {}
  manual_ip:
    static_ip: 192.168.1.238
    gateway: 192.168.1.1
    subnet: 255.255.255.0
    dns1: 192.168.1.250

captive_portal:
logger:
api:
ota:

substitutions:
  name: "Smart Outlet"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO03
      mode: INPUT_PULLUP
      inverted: True
    id: topButton
    on_release:
      - switch.toggle: relay2
      - switch.toggle: topLed
  - platform: gpio
    pin:
      number: GPIO05
      mode: INPUT_PULLUP
      inverted: True
    id: bottomButton
    on_release:
      - switch.toggle: relay1
      - switch.toggle: bottomLed

switch:
  - platform: gpio
    name: "Smart Outlet Top"
    pin: GPIO13
    id: relay2
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    name: "Smart Outlet Bottom"
    pin: GPIO12
    id: relay1
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    name: "Smart Outlet USB"
    pin: GPIO15
    id: relay3
    restore_mode: RESTORE_DEFAULT_OFF
  - platform: gpio
    restore_mode: RESTORE_DEFAULT_OFF
    id: topLed
    pin:
      number: GPIO4
      inverted: false
  - platform: gpio
    restore_mode: RESTORE_DEFAULT_OFF
    id: bottomLed
    pin:
      number: GPIO14
      inverted: false