esphome:
  name: smartplug2
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret ssid
  password: !secret password
  fast_connect: on
  ap:
    ssid: "${name} Fallback Hotspot"
    password: ""

captive_portal:
logger:
api:
ota:

substitutions:
  name: "Smart Plug 2"

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO13
      mode: INPUT_PULLUP
      inverted: True
    id: button
    on_release:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: "${name}"
    pin: GPIO12
    id: relay
    on_turn_on:
      - switch.turn_on: led
    on_turn_off:
      - switch.turn_off: led
    restore_mode: RESTORE_DEFAULT_ON
  - platform: gpio
    restore_mode: RESTORE_DEFAULT_ON
    id: led
    pin:
      number: GPIO4
      inverted: true

