substitutions:
  name: usbswitch
  upper_devicename: "USB Relay"
  static_ip: 192.168.1.56

esphome:
  name: ${name}

esp8266:
  early_pin_init: false
  board: esp01_1m

wifi:
  networks:
  - ssid: !secret ssid
    password: !secret password
    bssid: 9C:05:D6:37:4A:30
  fast_connect: off
  power_save_mode: none
  output_power: 20dB
  manual_ip:
    static_ip: ${static_ip}
    gateway: !secret gateway
    subnet: !secret subnet
    dns1: !secret dns1

captive_portal:
logger:
api:
  #reboot_timeout: 0s
ota:

#status_led:
#  pin:
#    number: GPIO16 # Blue LED

switch:
  # Relay
  - platform: gpio
    restore_mode: ALWAYS_ON
    id: relay
    pin: GPIO5

  # Green LED
  - platform: gpio
    pin: GPIO14
    id: green_led
    inverted: false # start off

  # Switch template to link relay and green LED states
  # LED is on when relay is off
  - platform: template
    id: "${name}_relay"
    name: $upper_devicename
    lambda: |-
      if (id(relay).state) {
        return true;
      } else {
        return false;
      }
    turn_on_action:
        - switch.turn_off:
            id: green_led
        - switch.turn_on:
            id: relay
    turn_off_action:
        - switch.turn_off:
            id: green_led
        - switch.turn_off:
            id: relay

## Button
#binary_sensor:
#  - platform: gpio
#    id: button
#    pin:
#      number: GPIO04
#      mode: INPUT_PULLUP
#      inverted: True
#    on_press:
#      - switch.toggle: "${name}_relay"