esphome:
  name: wt32-eth01

esp32:
  board: esp32dev
  framework:
    type: arduino

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16
  manual_ip:
    static_ip: ${static_ip}
    gateway: !secret gateway
    subnet: !secret subnet
    dns1: !secret dns1

substitutions:
  static_ip: 192.168.1.57
  friendly_name: "WT32-ETH01"

logger:
api:
ota:

remote_receiver:
  pin: 
    number: GPIO5
  dump:
    - rc_switch
 # Settings to optimize recognition of RF devices
  tolerance: 50%
  filter: 250us
  idle: 4ms
  buffer_size: 2kb

remote_transmitter:
  pin: GPIO17
  carrier_duty_percent: 100

switch:
  - platform: template
    name: Case Lights
    assumed_state: true
    optimistic: true
    lambda: |-
      return {};
    turn_on_action:
      - delay: 200ms
      - remote_transmitter.transmit_rc_switch_raw:
          code: '0100001110100100000000011'
          protocol: 1
          repeat: 3
    turn_off_action:
      - delay: 500ms
      - remote_transmitter.transmit_rc_switch_raw:
          code: '0100001110100100000000111'
          protocol: 1
          repeat: 5